services:
  pullarr:
    image: kirantheram/mangarr:latest
    container_name: pullarr
    ports:
      - "6997:6997"
    volumes:
      - ./data/pullarr-config:/config
      - ./data/comics:/comics
    restart: unless-stopped
